version: '1'

services:
  postgres_18:
    image: postgres:18.0-alpine3.22
    container_name: database_migration_poc_postgres_18
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - postgres_18_data:/var/lib/postgresql/data
    networks:
      - database-migration-poc

volumes:
  postgres_18_data:

networks:
  database-migration-poc:
    driver: bridge